name: sane_brushes
description: Brush engines and presets.
publish_to: none
version: 0.1.0
environment:
  sdk: ^3.13.0
resolution: workspace
dependencies:
  flutter:
    sdk: flutter
  sane_ink:
    path: ../sane_ink
dev_dependencies:
  flutter_test:
    sdk: flutter
