#!/usr/bin/env node
// Renders issues/*.json into docs/backlog/ (README index + one Markdown file per area) and prints a compact index.
// Usage: node scripts/render-issues.mjs [--index-only]
import { readFileSync, readdirSync, writeFileSync, mkdirSync, rmSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const ISSUES_DIR = join(ROOT, 'issues');
const OUT = join(ROOT, 'docs', 'backlog');
const indexOnly = process.argv.includes('--index-only');

const files = readdirSync(ISSUES_DIR).filter(f => f.endsWith('.json') && !['labels.json', 'milestones.json', '.published.json'].includes(f)).sort();
const issues = files.flatMap(f => JSON.parse(readFileSync(join(ISSUES_DIR, f), 'utf8')).map(i => ({ ...i, _file: f })));
const byKey = new Map(issues.map(i => [i.key, i]));
const published = existsSync(join(ISSUES_DIR, '.published.json')) ? JSON.parse(readFileSync(join(ISSUES_DIR, '.published.json'), 'utf8')) : {};
const ref = k => published[k] ? `#${published[k].number}` : `\`${k}\``;
const link = k => byKey.has(k) ? `[${k}](${byKey.get(k).areas[0]}.md#${k.toLowerCase()})` : `\`${k}\``;

const compact = issues.map(i => `${i.key} | ${i.type} | ${i.priority} | ${i.milestone} | ${i.platforms.join(',')} | ${i.areas.join(',')} | ${i.size} | parent=${i.parent || '-'} | ${i.title}`);
console.log(compact.join('\n'));
console.log(`\n${issues.length} issues`);
if (indexOnly) process.exit(0);

// Remove only files this script generates. docs/backlog/ also holds hand-written, committed
// reports (DEDUP-REPORT.md and friends); wiping the directory silently deleted them.
mkdirSync(OUT, { recursive: true });
const GENERATED = /^(README\.md|[a-z0-9-]+\.md)$/;
const KEEP = new Set(['DEDUP-REPORT.md']);
for (const f of readdirSync(OUT)) {
  if (KEEP.has(f) || !GENERATED.test(f)) continue;
  rmSync(join(OUT, f), { force: true });
}

const areas = [...new Set(issues.map(i => i.areas[0]))].sort();
const childrenOf = k => issues.filter(i => i.parent === k);
const tree = (k, depth) => childrenOf(k).map(c => `${'  '.repeat(depth)}- ${link(c.key)} **${c.title}** · ${c.priority} · ${c.type} · ${c.size} · ${c.milestone}\n${tree(c.key, depth + 1)}`).join('');

for (const a of areas) {
  const list = issues.filter(i => i.areas[0] === a).sort((x, y) => x.key.localeCompare(y.key));
  const epics = list.filter(i => i.type === 'epic');
  let md = `# Backlog — area: ${a}\n\n${list.length} issues. Generated from \`issues/*.json\` by \`scripts/render-issues.mjs\`; do not edit by hand.\n\n## Tree\n\n`;
  for (const e of epics) md += `- ${link(e.key)} **${e.title}** (epic · ${e.milestone})\n${tree(e.key, 1)}`;
  const orphans = list.filter(i => i.type !== 'epic' && !byKey.has(i.parent || ''));
  if (orphans.length) md += `\n### Without parent\n${orphans.map(o => `- ${link(o.key)} ${o.title}`).join('\n')}\n`;
  md += `\n---\n\n## Issues\n\n`;
  for (const i of list) {
    md += `### ${i.key}\n\n<a id="${i.key.toLowerCase()}"></a>\n\n**${i.title}**\n\n`;
    md += `| Field | Value |\n|---|---|\n| GitHub | ${published[i.key] ? `#${published[i.key].number}` : 'not published yet'} |\n| Type | ${i.type} |\n| Priority | ${i.priority} |\n| Milestone | ${i.milestone} |\n| Platforms | ${i.platforms.join(', ')} |\n| Areas | ${i.areas.join(', ')} |\n| Size | ${i.size} |\n| SDLC | ${i.sdlc} |\n| Parent | ${i.parent ? link(i.parent) : '—'} |\n| Depends on | ${(i.depends_on || []).map(link).join(', ') || '—'} |\n| Security controls | ${(i.security || []).map(s => `\`${s}\``).join(', ') || '—'} |\n| Extra labels | ${(i.labels_extra || []).join(', ') || '—'} |\n\n`;
    md += i.body.replace(/\{\{(SN-[A-Z0-9]{2,8}-\d{3})\}\}/g, (_, k) => link(k)).replace(/^## /gm, '#### ') + '\n\n---\n\n';
  }
  writeFileSync(join(OUT, `${a}.md`), md);
}

const count = (fn) => issues.reduce((m, x) => { const k = fn(x); (Array.isArray(k) ? k : [k]).forEach(kk => m[kk] = (m[kk] || 0) + 1); return m; }, {});
const table = (title, obj) => `### ${title}\n\n| ${title} | Count |\n|---|---|\n${Object.entries(obj).sort((a, b) => b[1] - a[1]).map(([k, v]) => `| ${k} | ${v} |`).join('\n')}\n\n`;
let readme = `# Backlog index\n\n${issues.length} issues (${issues.filter(i => i.type === 'epic').length} epics) across ${areas.length} areas. Generated by \`scripts/render-issues.mjs\` from \`issues/*.json\` — the JSON is the source of truth; GitHub issues are created from it by \`scripts/publish-issues.mjs\`.\n\n`;
readme += `## Areas\n\n| Area | Issues | Epic |\n|---|---|---|\n` + areas.map(a => { const l = issues.filter(i => i.areas[0] === a); const e = l.find(i => i.type === 'epic'); return `| [${a}](${a}.md) | ${l.length} | ${e ? `${e.key} — ${e.title}` : '—'} |`; }).join('\n') + '\n\n';
readme += table('Priority', count(i => i.priority)) + table('Milestone', count(i => i.milestone)) + table('Platform', count(i => i.platforms)) + table('Type', count(i => i.type)) + table('Size', count(i => i.size)) + table('SDLC phase', count(i => i.sdlc));
readme += `## p0 issues\n\n${issues.filter(i => i.priority === 'p0').map(i => `- ${link(i.key)} ${i.title} (${i.milestone})`).join('\n')}\n`;
writeFileSync(join(OUT, 'README.md'), readme);
console.error(`wrote docs/backlog/ (${areas.length} area files)`);
